--- 
- hosts: webservers 
  user: ansible 
  become: yes 
  connection: ssh 
  tasks: 
    - name: I want to create a List of Users 
      user: name='{{item}}' state=present 
      with_items:
        - Satya 
        - Kartik 
        - Sarma 
        - Gollakota 
        - Uppal 